export const Type = {
    ROOM_CREATE: {
        RESPONSE_FAILURE: "CHECK_ROOM_RESPONSE_FAILURE",
        RESPONSE_SUCCESS: "CHECK_ROOM_RESPONSE_SUCCESS"
    },
    ROOM_DESTROY: {
        RESPONSE_SUCCESS: "ROOM_DESTROY_RESPONSE_SUCCESS",
        RESPONSE_FAILURE: "ROOM_DESTROY_RESPONSE_FAILURE"
    },
    ROOM_JOIN: {
        RESPONSE_SUCCESS: "ROOM_JOIN_RESPONSE_SUCCESS",
        RESPONSE_FAILURE: "ROOM_JOIN_RESPONSE_FAILURE",
        REQUEST: "JOIN_ROOM_REQUEST",
        NOTIFY: "NOTIFY"
    },
    ROOM_EXIT: {
        RESPONSE_SUCCESS: "ROOM_EXIT_RESPONSE_SUCCESS",
        RESPONSE_FAILURE: "ROOM_EXIT_RESPONSE_FAILURE",
        REQUEST: "EXIT_ROOM_REQUEST",
        NOTIFY: "EXIT_ROOM_NOTIFICATION"
    },
    ROOM_DISCONNECTION:{
        NOTIFY: "ROOM_DESTROY_NOTIFICATION"
    }
}
export const labels = {
    NORMAL_SERVER_PROCESS: "NORMAL_SERVER_PROCESS",
    WEBRTC_PROCESS: "WEBRTC_SERVER"
};
